sudo: false
dist: trusty
language: python
install:
  - pip wheel --wheel-dir wheelhouse -r requirements.txt
  - pip install --no-index --find-links wheelhouse -r requirements.txt
cache:
  directories:
    - wheelhouse
git:
  depth: 3
python:
  - "2.7"
  - "3.5"
# command to install dependencies
install: "pip install -r requirements.txt"
# command to run tests
script: PYTHONPATH=. trial tests