sudo: false
dist: trusty
language: python
install:
  - mv wheelhouse wheelhouse.old
  - pip wheel --wheel-dir wheelhouse -r requirements.txt --find-links wheelhouse.old
  - pip install --no-index --find-links wheelhouse -r requirements.txt
cache:
  directories:
    - wheelhouse
git:
  depth: 3
python:
  - "2.7"
  - "3.5"
script: PYTHONPATH=. trial tests