language: python
python:
    - "2.6"
    - "2.7"
before_install: 
   - pip install -qpyflakes
   - find . -name '*.py' |xargs pyflakes
   - sudo apt-get -q install libssl-dev -y
install: pip install -q -r requirements.txt --use-mirrors
script: trial tests.py plugins