language: python
python:
    - "2.6"
    - "2.7"
before_install: 
   - pip install -q pyflakes
   - find . -name '*.py' |xargs pyflakes
install: pip install -q -r requirements.txt --use-mirrors
script: trial tests.py plugins